KS-2-5
NurGuru/KotlinSprint1 pull request #12
Opened 2023-03-15 12:42 UTC by NurGuru

2023-03-15 17:11 UTC, ievetrov requested changes
да, 5 задача со * не по теме урока.
можешь потом к ней вернуться при желании. 
а вообще это надо гуглить форматирование строки через String.format

2023-03-16 23:09 UTC, ievetrov requested changes

2023-03-16 23:09 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_5.kt
> +    var result = (1 + percent / 100).pow(timePeriod) * firstContribution
а чем обоснована тут изменяемая переменная?

2023-03-17 13:51 UTC, NurGuru commented on src/main/kotlin/lesson_2/lesson_2_task_5.kt
> +    var result = (1 + percent / 100).pow(timePeriod) * firstContribution
вроде ни чем ) не знаю даже почему так сделал) сейчас исправлю

2023-03-18 14:09 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_5.kt
> +    var result = (1 + percent / 100).pow(timePeriod) * firstContribution
лучше всегда изначально писать val)

2023-03-18 14:09 UTC, ievetrov approved these changes

2023-03-19 10:17 UTC, merged