KS-4-4
NurGuru/KotlinSprint1 pull request #21
Opened 2023-03-19 18:10 UTC by NurGuru

2023-03-20 10:15 UTC, ievetrov requested changes
1. надо стараться придерживаться принципа DRY (не повторяй себя)
то есть можно вынести определение четности/нечетности числа в булеан переменную и применять ее. isEven / !isEven

2. == это ссылочное сравнение (ссылки на объект в памяти). нам надо сравнивать просто значения

2023-03-20 10:39 UTC, NurGuru commented
> 1. надо стараться придерживаться принципа DRY (не повторяй себя)
>    то есть можно вынести определение четности/нечетности числа в булеан переменную и применять ее. isEven / !isEven
> 2. == это ссылочное сравнение (ссылки на объект в памяти). нам надо сравнивать просто значения

я честно говоря не допонял на счет первого пункта, но сделал как мог
а вот нас чет второго не понял к чему это относилось(

2023-03-20 21:59 UTC, ievetrov commented
> > 1. надо стараться придерживаться принципа DRY (не повторяй себя)
> >    то есть можно вынести определение четности/нечетности числа в булеан переменную и применять ее. isEven / !isEven
> > 2. == это ссылочное сравнение (ссылки на объект в памяти). нам надо сравнивать просто значения
> 
> я честно говоря не допонял на счет первого пункта, но сделал как мог а вот нас чет второго не понял к чему это относилось(

по 1 логика верная, но достаточно одной переменной 
`val isEven = day % 2 == 0`
и далее используешь этот булеан флаг. 
четный и НЕчетный
isEven и !isEven

по поводу второго пункта вот информация https://kotlinlang.ru/docs/equality.html
на результат не влияет (тк это примитивные типы). но различать способы сравнения нужно != и !== разные вещи

2023-03-21 05:49 UTC, NurGuru commented
> > > 1. надо стараться придерживаться принципа DRY (не повторяй себя)
> > >    то есть можно вынести определение четности/нечетности числа в булеан переменную и применять ее. isEven / !isEven
> > > 2. == это ссылочное сравнение (ссылки на объект в памяти). нам надо сравнивать просто значения
> > 
> > 
> > я честно говоря не допонял на счет первого пункта, но сделал как мог а вот нас чет второго не понял к чему это относилось(
> 
> по 1 логика верная, но достаточно одной переменной `val isEven = day % 2 == 0` и далее используешь этот булеан флаг. четный и НЕчетный isEven и !isEven
> 
> по поводу второго пункта вот информация https://kotlinlang.ru/docs/equality.html на результат не влияет (тк это примитивные типы). но различать способы сравнения нужно != и !== разные вещи

Все понял, спасибо)

2023-03-21 19:18 UTC, ievetrov approved these changes

2023-03-21 20:29 UTC, merged