KS-4-5
NurGuru/KotlinSprint1 pull request #22
Opened 2023-03-20 07:40 UTC by NurGuru

2023-03-20 22:00 UTC, ievetrov requested changes

2023-03-20 22:00 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val mayGo = breaks == false && teammates >= 55 && teammates < 70 && foodBoxes> MIN_FOOD_BOXES
Можно сократить `breaks == false` до `!breaks`, с помощью оператора отрицания. А breaks == true до просто breaks

2023-03-20 22:00 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +            && goodWeather==true || false
а для чего этот false?

2023-03-20 22:00 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +            ||breaks == true && teammates >= 55 && teammates == 70 && foodBoxes> MIN_FOOD_BOXES
Тут teammates одновременно и больше или равно 55, и равно 70. Слишком много условий

2023-03-21 06:04 UTC, NurGuru commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val mayGo = breaks == false && teammates >= 55 && teammates < 70 && foodBoxes> MIN_FOOD_BOXES
Понял, буду знать

2023-03-21 06:05 UTC, NurGuru commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +            && goodWeather==true || false
я думал так будет, работать условие для погоды в обоих случаях.
все испрвил

2023-03-21 19:50 UTC, ievetrov requested changes

2023-03-21 19:50 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +            && goodWeather == true
Лучше, но не совсем корректно.
В задаче представляется две группы условий - если нет повреждений (и еще ряд условий) и если незначительные повреждения (по сути с повреждениями и также ряд условий).
А у тебя они просто перечислены один за другим. Тут бы помогли скобки, чтобы показать приоритет.

Но давай попробуем сделать немного иначе:
 - создай переменную conditionWithNoBreaks и в нее собери все условия из для не поломанного корабля (обрати внимание, что условия "погода хорошая или погода плохая" в целом можно проигнорировать, так как это означает - "погода любая"
 - создай переменную conditionWithSmallBreaks и также собери в нее условия.

Тогда mayGo будет комбинацией созданных тобой переменных, а код более читаемым.

2023-03-21 21:09 UTC, ievetrov approved these changes
Отлично, проще же читается? )

2023-03-21 21:28 UTC, merged