KS-6-4
NurGuru/KotlinSprint1 pull request #31
Opened 2023-03-21 08:46 UTC by NurGuru

2023-03-21 19:49 UTC, ievetrov requested changes
задача не соответствует условию. 
также можно добавить информационных сообщений для пользователя (иначе непонятно что и когда вводить)

нужно запустить цикл и в нем запрашивать число для угадывания и сравнивать с выйгрышным. если угадал - выходить из него

2023-03-21 19:49 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_4.kt
> +    val gess = winNumber
а зачем тут дополнительная переменная?

2023-03-21 21:01 UTC, NurGuru commented on src/main/kotlin/lesson_6/lesson_6_task_4.kt
> +    val gess = winNumber
я уже забыл, почему) Но помню что  без нее в моем исполнении не работал код. Пойду исправлять)

2023-03-22 10:47 UTC, ievetrov requested changes

2023-03-22 10:47 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_4.kt
> +            println("Это была великолепная игра")
Уже лучше, но программа не завершает работу после сообщения "Это была великолепная игра". А продолжает ждать ввод, если это не последняя попытка

2023-03-23 12:18 UTC, ievetrov approved these changes

2023-03-23 13:07 UTC, merged