KS-6-5
NurGuru/KotlinSprint1 pull request #32
Opened 2023-03-21 15:09 UTC by NurGuru

2023-03-21 20:07 UTC, ievetrov requested changes
работает по условию верно. но если угадать например с первой попытки – цикл не останавливается и продолжает перезапускаться. это может повлечь трату ресурсов на большом объеме

2023-03-21 21:43 UTC, NurGuru commented
> работает по условию верно. но если угадать например с первой попытки – цикл не останавливается и продолжает перезапускаться. это может повлечь трату ресурсов на большом объеме

Блин, может я не понимаю чего-то, но когда я угадываю с первого раза, мне выдает сразу за циклом текст который.
я снова пришлю в бот ссылку на этот пуул реквест, не потому что наглый)) а потому что не знаю, вдруг этот ответ не увидишь)

2023-03-22 12:48 UTC, ievetrov commented
я поэтому и говорю, что по условию вроде как работает верно (видимости такую создает да)
с точки зрения работы алгоритма не верно. чтобы наглядно увидеть что происходит можешь логировать - расставить везде принты чтобы увидеть когда и с чем они вызываются.

2023-03-22 12:50 UTC, ievetrov requested changes

2023-03-22 12:50 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_5.kt
> +        attempt--
между 12 и 13 строчками напиши println c каким нить текстом и увеличь количество попыток до 10к например

а потом угадай с первого раза и посмотри что будет дальше

2023-03-23 03:40 UTC, NurGuru commented on src/main/kotlin/lesson_6/lesson_6_task_5.kt
> +        attempt--
все все, теперь понял)

2023-03-23 18:26 UTC, ievetrov approved these changes
великолепно)

2023-03-23 20:49 UTC, merged