KS-7-1
NurGuru/KotlinSprint1 pull request #33
Opened 2023-03-22 06:52 UTC by NurGuru

2023-03-22 15:16 UTC, ievetrov requested changes

2023-03-22 15:16 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_1.kt
> +    val symbol2 = (1..9).random().toString()
чем обосновано приведение к типа стринг тут?
либо почему не приведены в других символах?

2023-03-23 03:47 UTC, NurGuru commented on src/main/kotlin/lesson_7/lesson_7_task_1.kt
> +    val symbol2 = (1..9).random().toString()
выдавало ошибку, из-за типа переменной, именно во второй и в третьей букве, когда во второй поменял тип, ошибка ушла и в третьей.
думал может так можно

2023-03-23 12:20 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_1.kt
> +    val symbol2 = (1..9).random().toString()
можно. и нужно) в комменте к коду отпишу

2023-03-23 12:24 UTC, ievetrov requested changes

2023-03-23 12:24 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_1.kt
> +    val password = println(symbol1+symbol2+symbol3+symbol4+symbol5+symbol6)
вот тут вопросики. 
ты вызываешь println и присваешь эту функцию в новую переменную. выведи тип переменной password – это уже будет не строка

и второе по поводу .toString()
складывая символы ты хочешь сделать список. но компилятор ругается, потому что хочешь в него положить и строки и чары.

но ведь есть известный способ не создавать список, а просто сделать строку, в которой печатаются все символы из переменных

2023-03-23 13:12 UTC, NurGuru commented on src/main/kotlin/lesson_7/lesson_7_task_1.kt
> +    val password = println(symbol1+symbol2+symbol3+symbol4+symbol5+symbol6)
а блин ну да) четко, щас переделаю

2023-03-23 22:00 UTC, ievetrov approved these changes

2023-03-24 12:01 UTC, merged