KS-7-2
NurGuru/KotlinSprint1 pull request #34
Opened 2023-03-22 07:21 UTC by NurGuru

2023-03-22 15:21 UTC, ievetrov requested changes
у тебя три строки практически идентичны друг другу. не соблюден принцип DRY и код повторяется

алгоритм будет работать оптимальнее, если изменить цикл. если сначала создавать и запрашивать, а потом проверять. помнишь какой цикл так умеет?

2023-03-23 03:56 UTC, NurGuru commented
> у тебя три строки практически идентичны друг другу. не соблюден принцип DRY и код повторяется
> 
> алгоритм будет работать оптимальнее, если изменить цикл. если сначала создавать и запрашивать, а потом проверять. помнишь какой цикл так умеет?

теперь наконец-то понял до конца зачем do while нужен)

2023-03-23 03:57 UTC, merged

2023-03-23 03:59 UTC, NurGuru commented
> > у тебя три строки практически идентичны друг другу. не соблюден принцип DRY и код повторяется
> > алгоритм будет работать оптимальнее, если изменить цикл. если сначала создавать и запрашивать, а потом проверять. помнишь какой цикл так умеет?
> 
> теперь наконец-то понял до конца зачем do while нужен)

блин я случайно мердж сделал

2023-03-23 12:24 UTC, ievetrov commented
окей принято)