KS-7-5 что-то я не вывожу эту задачу, можно подсказать ход какой даль…
NurGuru/KotlinSprint1 pull request #37
Opened 2023-03-23 04:51 UTC by NurGuru

…ше?) я тут по всякому думал, но ничего(

2023-03-23 21:34 UTC, ievetrov requested changes

2023-03-23 21:34 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +    for (i in passwordLength downTo 0) {
Цикл - правильный ход мысли )

2023-03-23 21:34 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +    val number = (1..9).random().toString()
(1..9) - это литерал для создания IntRange, то есть в месте вызова появится объект IntRange;
Range'ы можно объединять оператором +;
тебе нужно выбирать один рандомный из **всех** возможных символов;
строки поддерживают оператор +=

Попробуй сложить пазл ))

2023-03-24 14:35 UTC, NurGuru commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +    val number = (1..9).random().toString()
не могу это задание доделать никак
выручи пожалуйста)

2023-03-24 19:50 UTC, ievetrov requested changes

2023-03-24 19:50 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +    val letterUp = ('A'..'Z')
Для начала давай получим список всех символов:
```Kotlin
val symbols = (1..9) + ('a'..'z') + ('A'..'Z')
```
А теперь доставай оттуда символы

2023-03-26 12:07 UTC, ievetrov requested changes

2023-03-26 12:07 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +            var password = symbols.random().toString()
во-1 у тебя на каждой итерации цикла заново создается переменная `password`
поэтому никогда там целый пароль не окажется, так как всегда записывается по одному символу и он же перезатирается

2023-03-26 12:07 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson_7_task_5.kt
> +            var password = symbols.random().toString()
поэтому для начала надо вынести создание переменной пароля проинициализировав пустой строкой

2023-03-26 16:43 UTC, ievetrov approved these changes
великолепно!

2023-03-27 05:11 UTC, merged