KS-8-2
NurGuru/KotlinSprint1 pull request #40
Opened 2023-03-23 06:38 UTC by NurGuru

2023-03-23 06:40 UTC, NurGuru commented
ошибся

2023-03-23 14:07 UTC, ievetrov requested changes

2023-03-23 14:07 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_3.kt
> +    if (arrayOfIngredients.indexOf("$searchingIngredient") >= 0) {
тут не нужно делать интерполяцию. достаточно инпут передавать как есть

2023-03-24 20:08 UTC, ievetrov requested changes
Не корректное имя Pull Request'а

2023-03-24 20:08 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_2.kt
> +fun main() {
Для чего тут второе задание?

2023-03-24 20:08 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_3.kt
> +    if (arrayOfIngredients.indexOf(searchingIngredient) >= 0) {
тут все корректно

2023-03-25 08:26 UTC, closed without merging