KS-9-2
NurGuru/KotlinSprint1 pull request #45
Opened 2023-03-27 04:46 UTC by NurGuru

2023-03-27 12:02 UTC, ievetrov requested changes

2023-03-27 12:02 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_1.kt
> +    if (askToAdd == "Да") {
как можно решить проблему, если я ввожу слово с маленькой буквы? (в таком случае не работает)

2023-03-27 12:08 UTC, NurGuru commented on src/main/kotlin/lesson_9/lesson_9_task_1.kt
> +    if (askToAdd == "Да") {
> как можно решить проблему, если я ввожу слово с маленькой буквы? (в таком случае не работает)

я еще думал может сразу сделать так)

2023-03-27 16:42 UTC, ievetrov requested changes

2023-03-27 16:42 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_1.kt
> +    val ingredients = mutableListOf("яйцо", "сметана", "хлеб")
А почему решение задачи 2 в файле lesson_9_task_1.kt?
Ниже же вроде корректный файл лежит

2023-03-27 16:42 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_2.kt
> +    if (askToAdd == "Да" || askToAdd == "да") {
еще можно askToAdd.lowercase()

2023-03-27 17:28 UTC, NurGuru commented on src/main/kotlin/lesson_9/lesson_9_task_1.kt
> +    val ingredients = mutableListOf("яйцо", "сметана", "хлеб")
> А почему решение задачи 2 в файле lesson_9_task_1.kt? Ниже же вроде корректный файл лежит

да я там че-то косякнул, ветку новую завел и писать продолжил в файле другой задачи и там же закомитил , потом что-то пытался исправить но похоже не вышло)

2023-03-28 05:27 UTC, ievetrov requested changes

2023-03-28 05:27 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_1.kt
> +    val ingredients = mutableListOf("яйцо", "сметана", "хлеб")
Не страшно. Вообще git тема непростая, и мало того что поначалу нужно понять как он работает, так на каждом новом месте работы еще свои правила )

Но что точно могу сказать - не стоит смешивать работу над несколькими задачами в одной ветке. Давай удалим этот файл в этой ветке (lesson9-task2).Иначе конфликты будут с веткой lesson9-task1

2023-03-28 05:27 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_2.kt
> +    if (askToAdd == "Да"|| askToAdd=="Да".lowercase()) {
Так а ты же ничего не сократил так )
Посмотри еще внимательнее на мой коммент.

> еще можно askToAdd.lowercase()

2023-03-28 07:16 UTC, NurGuru commented on src/main/kotlin/lesson_9/lesson_9_task_2.kt
> +    if (askToAdd == "Да"|| askToAdd=="Да".lowercase()) {
> Так а ты же ничего не сократил так ) Посмотри еще внимательнее на мой коммент.
> 
> > еще можно askToAdd.lowercase()

блин.. я этот lowercase куда только не ставил, не работает что то

2023-03-28 10:46 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_2.kt
> +    if (askToAdd == "Да"|| askToAdd=="Да".lowercase()) {
lowercase() приводит строку к нижнему регистру, то есть "Да" он превратит в "да", ну и "да" также превратит в "да" (оставит без изменений то есть).
Вот пример:
https://pl.kotl.in/XXa81HibF

2023-03-28 11:41 UTC, NurGuru commented on src/main/kotlin/lesson_9/lesson_9_task_2.kt
> +    if (askToAdd == "Да"|| askToAdd=="Да".lowercase()) {
да блин! у меня было "да" с большой буквы вот так ( askToAdd. == "Да") и я вокруг него повсюду вставлял этот lowercase)) 
все исправил

2023-03-28 11:52 UTC, ievetrov approved these changes
![giphy](https://user-images.githubusercontent.com/34489023/228227367-294d28eb-5a1f-441c-82a7-834014e08c17.gif)

2023-03-28 13:26 UTC, closed without merging