KS-9-5
NurGuru/KotlinSprint1 pull request #48
Opened 2023-03-27 06:14 UTC by NurGuru

я тут опять застрял
не могу понять как сравнить элементы между собой
и как первый эелемент с большой сделать (я там по всякому пробовал, тут в файле просто последние муки оставил и отправил))
ну и так же как и в предыдущем задании по алфавиту не знаю как распределить

2023-03-27 15:06 UTC, ievetrov requested changes

2023-03-27 15:06 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    var ingredients = mutableListOf(readln(), readln(), readln(), readln(), readln())
вот так делать не надо. это прямое повторение кода. если видишь повторяющиеся элементы, сразу надо рассмотреть как сделать что-то в цикле)

собственно тут можно просто на каждой итерации добавлять в список элементы (что должно быть вроде известно)

далее.. насчет повторов. посмотри что за коллекция не умеет хранить повторы и как в нее превратить твой текущий список?

2023-03-28 08:31 UTC, NurGuru commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    var ingredients = mutableListOf(readln(), readln(), readln(), readln(), readln())
один момент остался не смог сделать с заглавной буквы чтоб был элемент.
отдельно сделать получается но в общем списке не могу

2023-03-28 11:26 UTC, ievetrov requested changes

2023-03-28 11:26 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    ingredients=ingredients.sorted().toMutableSet()
То там, тот тут форматирование начало страдать (я про другие PR`ы), давай-ка повнимательней.
В Idea есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx)

2023-03-28 11:26 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    ingredients=ingredients.sorted().toMutableSet()
Решение правильное, но просто вопрос на засыпку ))
Как думаешь есть принципиальная разница между:
```Kotlin
ingredients.sorted().toMutableSet()
```
и
```Kotlin
ingredients.toMutableSet().sorted()
```
?
Что предпочтешь 🪑🪑

2023-03-28 11:26 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    ingredients.add(".")
Насчет последнего условия, давай подумаем логически:
>  – первое слово должно быть напечатано с заглавной буквы, в конце списка должна стоять точка.

"Первое" и "последнее" имеется в виду **после** сортировки, поэтому на этапе заполнения списка модифицировать их нет смысла.
Добавляя точку как последний элемент, ты не ставишь точку в конце. Имелось в виду - добавить точку в конец последнего слова, так что это не правильно. В следующем коммента как правильно )

2023-03-28 11:26 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    ingredients.add(".")
Как нам модифицировать строки?
Строки в Kotlin это по сути **неизменяемый массив символов**. Ты можешь прочитать любой символ по порядковому номеру. Например:

```Kotlin
print("Hello"[0])
```
Выведет H.

Таким образом получить первую букву первого слова из списке, можно так: `ingredients[0][0]`.
Но так как строки не изменяемы, мы не можем сделать просто:
```
ingredients[0][0] = ingredients[0][0].uppercase()
```
То есть - **нельзя редактировать символы в строке**, но можно создать новую строку.
```
a[0] = a[0][0].uppercase() + _тут остаток строки_
```

И тебе останется только понять, что делает экстеншн функция [`substring(...)`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/substring.html), чтобы успешно решить задачу

2023-03-28 11:51 UTC, NurGuru commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    ingredients=ingredients.sorted().toMutableSet()
понял, исправлюсь 
забываю блин про это

2023-03-28 12:02 UTC, NurGuru commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    ingredients=ingredients.sorted().toMutableSet()
ну  я как понял этот метод sorted первращает в переменную в List, а нам надо чтобы он был MutableSet. поэтому сперва этот список сортируем по алфовиту(превращая в List) и потом уже обратно.
как то так думаю)

2023-03-28 13:25 UTC, NurGuru commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    ingredients.add(".")
Вроде все сделал)

2023-03-28 13:28 UTC, ievetrov approved these changes

2023-03-28 13:28 UTC, merged