KS-10-2
NurGuru/KotlinSprint1 pull request #50
Opened 2023-03-27 07:06 UTC by NurGuru

2023-03-27 15:36 UTC, ievetrov requested changes
у тебя тут вообще вся логика в отдельную функцию вынесена. а нужно как обычно в мейне и только валидацию вынести. она будет проверять только длину и возвращать булеан результата валидации

2023-03-28 13:04 UTC, ievetrov requested changes

2023-03-28 13:04 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +fun validation(passwordLength: Int): Boolean {
В целом - вынесение логики в функции хорошая практика.
Но[ функции нужно называть глаголом](https://kotlinlang.org/docs/coding-conventions.html#choose-good-names), типа validate(), validatePassword().
Но параметр очень странный - длина пароля.

Если бы заказчик сказал тебе добавить еще проверку на символы (к примеру: буквы и цифры должны присутствовать), а ты передаешь длину - пришлось бы больше кода переписывать. Давай передавать пароль тогда хотя бы в validate() , раз уж вынес в функцию.

2023-03-28 17:48 UTC, NurGuru commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +fun validation(passwordLength: Int): Boolean {
> В целом - вынесение логики в функции хорошая практика. Но[ функции нужно называть глаголом](https://kotlinlang.org/docs/coding-conventions.html#choose-good-names), типа validate(), validatePassword(). Но параметр очень странный - длина пароля.
> 
> Если бы заказчик сказал тебе добавить еще проверку на символы (к примеру: буквы и цифры должны присутствовать), а ты передаешь длину - пришлось бы больше кода переписывать. Давай передавать пароль тогда хотя бы в validate() , раз уж вынес в функцию.

я что-то не очень понял на счет параметра. 
я как понял надо было сделать функцию которая будет проверять длину пароля, для этого ей надо принимать данные о этой длине (через параметр- верно?) и надо как-то этот параметр в функции назвать, думал логично так и назвать (длинаПароля). 
я пул реквест отправлю, потому что не знаю коменты сами по себе видишь или только если зайдешь по ссылке с бота.

2023-03-28 17:48 UTC, NurGuru commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +fun validation(passwordLength: Int): Boolean {
и если что это написал не с высокомерным вайбом и претензией, а чтоб показать то как я понимаю эту тему

а то перечитал и каким то злобным показался ответ))

2023-03-28 23:00 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +fun validation(passwordLength: Int): Boolean {
> я как понял надо было сделать функцию которая будет проверять длину пароля, для этого **ей надо принимать данные о этой длине (через параметр- верно?)** и надо как-то этот параметр в функции назвать, думал логично так и назвать (длинаПароля).

Да, можно и просто длину передать, но лучше сам пароль в виде строки, и уже в функции посчитать сколько в нем символов.
```Kotlin
fun checkPassword(password: String): Boolean {
// тут проверяешь длину
// а если еще понадобится что-то проверять, то ты просто 
// допишешь сюда код, и больше никуда не будешь его писать, 
// и переименовывать не придется - это удобно )
}
```

2023-03-28 23:01 UTC, ievetrov requested changes

2023-03-28 23:01 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +fun validate(passwordLength: Int): Boolean {
```Kotlin
fun checkPassword(password: String): Boolean {
// тут проверяешь длину
// а если еще понадобится что-то проверять, то ты просто 
// допишешь сюда код, и больше никуда не будешь его писать, 
// и переименовывать не придется - это удобно )
}
```

2023-03-29 08:36 UTC, NurGuru commented on src/main/kotlin/lesson_10/lesson_10_task_2.kt
> +fun validate(passwordLength: Int): Boolean {
все понял, спасибо)

2023-03-29 18:59 UTC, ievetrov approved these changes

2023-03-29 20:03 UTC, merged