KS-10-3
NurGuru/KotlinSprint1 pull request #51
Opened 2023-03-27 07:48 UTC by NurGuru

не мог понять как добавить рандомный спец символ
подскажи пожалуйста

2023-03-27 15:41 UTC, ievetrov requested changes
ну для начала символы из условия неплохо было бы добавить в код) в каком виде можно их хранить?

2023-03-28 09:22 UTC, NurGuru commented
я добавил

> ну для начала символы из условия неплохо было бы добавить в код) в каком виде можно их хранить?

я добавил символы, сделал сплит, но честно говоря некоторые символы удалить пришлось, не знаю это случайно они там у тебя или спецом, чтоб сложнее было, но с ними не получалось (там " и \ и еще что-то помоему

2023-03-28 16:05 UTC, ievetrov commented
> я добавил
> 
> > ну для начала символы из условия неплохо было бы добавить в код) в каком виде можно их хранить?
> 
> я добавил символы, сделал сплит, но честно говоря некоторые символы удалить пришлось, не знаю это случайно они там у тебя или спецом, чтоб сложнее было, но с ними не получалось (там " и \ и еще что-то помоему

да. есть такая штука – экранирование символов с помощью обратного слэша. таким образом символ не будет аффектить строку

2023-03-28 16:07 UTC, ievetrov requested changes
кажется все работает) осталось только добавить все остальные символы, используя экранирование

2023-03-29 09:42 UTC, ievetrov approved these changes
все верно!

2023-03-29 11:59 UTC, merged