KS-10-4
NurGuru/KotlinSprint1 pull request #52
Opened 2023-03-28 09:46 UTC by NurGuru

может есть и поизящнее решение, но я очень горжусь, что хотя бы так сделал)))
часа полтора именно над этой задачей  вчера сидел) сегодня додумался через ду уайл сделать
вроде все работает)

2023-03-28 18:05 UTC, ievetrov requested changes
проведена хорошая работа, но крупные вещи с первого раза редко получаются сразу прекрасными) давай порефакторим)

2023-03-28 18:05 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_4.kt
> +    } while (newRound(humanWins) == "да")
вот тут немного запутанная проверка. неясно функциональное предназначение, сложно читается. 
по сути просто проверяем что ввел пользователь. тут достаточно сразу читать консоль и проверять ответ

вместо метода newRound, давай лучше добавим метод проверки правильности ответа. вынеся в него условие, которое написано выше в цикле. функция будет проверять и возвращать булеан результат

2023-03-28 21:44 UTC, NurGuru commented on src/main/kotlin/lesson_10/lesson_10_task_4.kt
> +    } while (newRound(humanWins) == "да")
извини пожалуйста, но я ничего не понял) я по разному пытался сделать то что написал ты- все перестает работать

2023-03-30 19:35 UTC, ievetrov requested changes

2023-03-30 19:35 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_4.kt
> +    } while (newRound(humanWins) == "да")
не так сформулировал, хотел просто чтобы newRound(humanWins) возвращала boolean, сравнение с "да" выглядит просто странно. Вот если бы метод назывался getUserAnswer() или как то так.

Давай сравнение с да уберем, мы же его и так делаем внутри newRound, пусть он и возвращает boolean

2023-03-30 19:35 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_4.kt
> +            println("Победило человечество!!!")
println("Победило человечество!!! \n")

2023-03-31 09:55 UTC, ievetrov approved these changes

2023-04-01 07:38 UTC, merged