KS-11-3 помоги))
NurGuru/KotlinSprint1 pull request #57
Opened 2023-03-29 21:16 UTC by NurGuru

все таки без подробных инструкций сложно пока
я минут 40 разное пробовал, но все таки ничего толкового не выходит.
не могу понять для нажимания на автарку функцию делать или нет, и как это все сделать
в итоге просто закоментил что было на тот момент и отправил

2023-03-30 05:46 UTC, ievetrov requested changes

2023-03-30 05:46 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +//    fun showAvatar(avatar: List<String>, namber: Int, nameOfMember:String) {
Тут не нужно усложнять

Создай класс для сущности карточки комнаты с такими полями: 
- строка с ссылкой на картинку обложки
- строка для заголовка комнаты
- список объектов участников

Для списка участников создай класс User. С полями: 
- никнейм, 
- url адрес аватара 
- текстовый статус говорящего с тремя элементами из условия

В main создй список экземпляров комнат с произвольными данными и выведи в консоль.

2023-03-30 10:24 UTC, NurGuru commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +//    fun showAvatar(avatar: List<String>, namber: Int, nameOfMember:String) {
я вроде сделал, только не пойму как статусы говорящего добавить, чтоб потом можно было по 1 вытаскивать их

2023-03-30 19:23 UTC, ievetrov requested changes

2023-03-30 19:23 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +class User(val name: String, val avatar: String) {
Можно просто текстовое поле status, но так как статусы нам известны, лучше подойдет enum.

2023-03-30 19:23 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +    println(user4.name)
> После проектирования создай **список объектов карточек** с несколькими “комнатами” с произвольными данными.

2023-03-30 19:23 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +//    fun showAvatar(avatar: List<String>, namber: Int, nameOfMember:String) {
просто поле status

2023-03-31 10:15 UTC, NurGuru commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +class User(val name: String, val avatar: String) {
мне уже стыдно, но я не смог enum никуда пристроить, может в уроках где было а я забыл

я

2023-03-31 14:37 UTC, ievetrov requested changes

2023-03-31 14:37 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +class RoomCard(val img: String1, val roomName: String1, val members: List<User>) {}
Давай так
```Kotlin
class RoomCard(
    val img: String,
    val roomName: String,
    val members: List<User>,
)
```

2023-03-31 14:37 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +import kotlin.String as String1
зачем? )

2023-03-31 14:37 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +    val status: String = "разговаривает,микрофон выключен,пользователь заглушен,"
> Рядом с аватаркой отображается текстовый бейдж с одним из возможных статусов говорящего: “разговаривает”, “микрофон выключен”, “пользователь заглушен

Один из статусов. То есть при создании просто передавай в строку "разговаривает" или "микрофон выключен" и т.д. Это простой путь )

Но раз уж сказал про Enum:
```Kotlin

enum class UserStatus(val label: String) {
    TALK("разговаривает"),
    MIC_OFF(".."),
    USER_MUTED("..");
}

class User(
    val name: String,
    val avatar: String,
    val status: UserStatus,
)
```

2023-03-31 14:37 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +    val room2 = RoomCard("картинка автара комнаты", "Russian Speaking Club", listOf(user3, user4))
тут требуется список, почитай условие - я специально bold`ом подсветил в комменте выше, можешь в целом сразу создать список:

```Kotlin
    val user1 = User_("John", "картинка аватара пользователя")
    val user2 = User_("Steve", "картинка аватара пользователя")
    val user3 = User_("Oleg", "картинка аватара пользователя")
    val user4 = User_("Sasha", "картинка аватара пользователя")

    val rooms = listOf(
        RoomCard(
            img = "картинка автара комнаты",
            roomName = "Russian Speaking Club", 
            members = listOf(user3, user4)
        ),
        //...
    )
    rooms.forEach { 
        println(it.roomName, ....)
    }
```

2023-04-01 19:07 UTC, ievetrov requested changes

2023-04-01 19:07 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +
тут и в конце файла лишние переносы строки

2023-04-01 19:07 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_3.kt
> +    MIC_OFF(".."),
тут нормальные параметры вместо .. поставь

2023-04-02 11:56 UTC, ievetrov approved these changes

2023-04-02 20:28 UTC, merged