KS-12-5
NurGuru/KotlinSprint1 pull request #62
Opened 2023-04-01 22:55 UTC by NurGuru

Подскажи пожалуйста как добавить в список созданные в цикле объекты

2023-04-01 23:51 UTC, NurGuru commented
> Подскажи пожалуйста как добавить в список созданные в цикле объекты

я уже после того как первый пул реквест отправил еще посидел, вроде получилось

2023-04-02 11:53 UTC, ievetrov requested changes

2023-04-02 11:53 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +    println(middleDayTemperature)
Давай немного о пользователе позаботимся ))
Помогу тебе:
```Kotlin
    println("Средняя температура днем: $, ночью: $")
    println("среднее атмосферное давление: $")
    println("Дождливых дней: $")

```

2023-04-02 11:53 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +            rainyDays += 1
Ты сделал одним циклом и создание и подсчет.
Конечно для решения задачи это норм, но как делают чаще всего в приложениях:

1) Получают данные из внешнего источника (например сервера) в каком-нибудь формате
2) Преобразуют этот формат в объекты нашего приложения (WeatherChange5 в нашем случае)
3) Манипулируют с этими данными (например считают среднее значение)

Давай отделим создание списка WeatherChange5 от подсчета

2023-04-02 11:53 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +
Запасные пустые строки в конце? ))
Кстати, советую смотреть на пул реквест перед отправкой, это полезная практика не только в рамках нашего курса. но и на работе

2023-04-03 16:51 UTC, NurGuru commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +            rainyDays += 1
Подскажи пожалуйста, как данные из цикла вне цикла лучше посчитать? у меня всегда затык с этим, вроде уже пару раз возникал этот вопрос, но не могу найти где и как его решил. Я спецом пул реквест закинул так. Вот на этом моменте у меня возникают проблемы, где область видимости нужных мне вещей заканчивается))

2023-04-03 21:50 UTC, NurGuru commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +    println(middleDayTemperature)
а блин не увидел это, исправлю

2023-04-04 12:52 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +            rainyDays += 1
Область видимости локальных переменных внутри цикла заканчивается в конце цикла (переменная newDay).
Результатом выполнения твоего цикла является заполненный список list, с ним и нужно работать. 

Например: list.forEach {} или использовать еще один for

2023-04-05 06:02 UTC, ievetrov requested changes

2023-04-05 06:02 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +    list.forEach { middleDayTemperature += (it.dayTemperature) / 10 }
Можно в одном forEach для всех полей. И rainyDays там же

2023-04-05 12:57 UTC, ievetrov requested changes
Давай немного о пользователе позаботимся ))
Помогу тебе:
```Kotlin
    println("Средняя температура днем: $, ночью: $")
    println("среднее атмосферное давление: $")
    println("Дождливых дней: $")

```

2023-04-06 08:21 UTC, ievetrov approved these changes

2023-04-07 10:32 UTC, merged