KS-11-5
NurGuru/KotlinSprint1 pull request #78
Opened 2023-04-07 20:23 UTC by NurGuru

подскажи пожалуйста, в этом задании класс форум должен быть интерфейсом или абстрактным классом?
или вообще реализовать фабричный метод надо через Companion object (не знаю толком что это, но и такое читал)
просто очень хочется сделать это задание но что-то не выходит.
я по разному пробовал, решил уже так отправлю просто пул реквест чтоб спросить

2023-04-08 20:56 UTC, ievetrov requested changes
класс Форум обычный класс может быть вполне. применение фабрики заключается в том, чтобы внутри класса был метод, которые занимается созданием новых объектов (пользователей)

2023-04-09 13:38 UTC, NurGuru commented
> класс Форум обычный класс может быть вполне. применение фабрики заключается в том, чтобы внутри класса был метод, которые занимается созданием новых объектов (пользователей)

сделал чтоб условие задачи выполнялось, только вот написано было в условии использовать классы из первых двух задач, но только из первой использовал я

2023-04-10 16:34 UTC, ievetrov requested changes

2023-04-10 16:34 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +    fun newMessage(authorId: Int, authorName: String, message: String): String {
Message должен быть создаваемым объектом

2023-04-10 16:34 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +        return User1(id, login, password, mail)
id в User должен проставляться внутри createNewUser(). То есть внутри Forum хранится переменная, которая повышается каждый раз при создании пользователя.

2023-04-10 16:34 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +        println("$author: $message")
этот метод берет список сообщений который должен храниться внутри Forum, и печатать его

2023-04-10 16:34 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_1.kt
> +    val userOleg = User1(23, "MrOleg", "oleg0707", "oleg@mail.ru")
не надо редактировать старые классы, создай еще и положи в тот же файл таска с классом Forum

2023-04-10 21:24 UTC, NurGuru commented on src/main/kotlin/lesson_11/lesson_11_task_1.kt
> +    val userOleg = User1(23, "MrOleg", "oleg0707", "oleg@mail.ru")
> не надо редактировать старые классы, создай еще и положи в тот же файл таска с классом Forum

подскажи пожалуйста как из списка сообщений достать данные, чтоб они отображались нормально
все вроде сделал, а этот момент что-то не получается

2023-04-11 21:04 UTC, NurGuru commented
подскажи пожалуйста как из списка сообщений достать данные, чтоб они отображались нормально
все вроде сделал, а этот момент что-то не получается

2023-04-12 12:36 UTC, ievetrov requested changes

2023-04-12 12:36 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +        mainId+=+1
лишний +

2023-04-12 12:36 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +    var mainId: Int=0
форматирование (где пробелы?)

2023-04-12 12:36 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +        return User5(mainId, login, password, mail)
для пользователей тоже заведи список, как для сообщений

2023-04-12 12:36 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +        return NewMessage(authorId, authorName, message)
Вот тут прежде чем возвращать NewMessage(...), добавь его в список messages

2023-04-12 12:36 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +        for (i in messages) {
i - плохое название, может message?

2023-04-12 12:36 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +            var messageAuthorName= messages[1]
Зачем внутри цикла обращаться по индексу?

2023-04-12 20:43 UTC, NurGuru commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +            var messageAuthorName= messages[1]
я что-то совсем запутался, в printThread как обратиться к нужным элементам не могу понять

2023-04-14 20:02 UTC, ievetrov requested changes

2023-04-14 20:02 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +        return NewMessage(authorId, authorName, message)
Ты создал два NewMessage - один добавил в список, второй вернул

2023-04-14 20:02 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +//
пустой коммент

2023-04-14 20:02 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_5.kt
> +
лишние пробелы

2023-04-19 11:35 UTC, ievetrov approved these changes

2023-04-24 16:23 UTC, merged