KS-16-2
NurGuru/KotlinSprint1 pull request #80
Opened 2023-04-07 21:15 UTC by NurGuru

2023-04-08 21:07 UTC, ievetrov requested changes

2023-04-08 21:07 UTC, ievetrov commented on src/main/kotlin/lesson_16/lesson_16_task_2.kt
> +class Circle(protected val radius: Double) {
чем обусловлен протектед?) вопрос модульности у нас не стоит

2023-04-09 12:09 UTC, NurGuru commented on src/main/kotlin/lesson_16/lesson_16_task_2.kt
> +class Circle(protected val radius: Double) {
понял поменяю)

2023-04-10 12:49 UTC, ievetrov approved these changes

2023-04-10 19:31 UTC, merged