KS-16-4
NurGuru/KotlinSprint1 pull request #82
Opened 2023-04-10 12:34 UTC by NurGuru

2023-04-10 21:18 UTC, ievetrov requested changes

2023-04-10 21:18 UTC, ievetrov commented on src/main/kotlin/lesson_16/lesson_16_task_4.kt
> +    private var orderStatusChanging = false
а как влияет на функциональность этот флаг? (в контексте ТЗ)

2023-04-10 21:18 UTC, ievetrov commented on src/main/kotlin/lesson_16/lesson_16_task_4.kt
> +    fun changeStatus() {
функция должна принимать новый статус и устанавливать его

2023-04-10 21:18 UTC, ievetrov commented on src/main/kotlin/lesson_16/lesson_16_task_4.kt
> +    val number: Int,
есть смысл сделать приватными поля все

2023-04-10 21:29 UTC, NurGuru commented on src/main/kotlin/lesson_16/lesson_16_task_4.kt
> +    private var orderStatusChanging = false
ну чтобы как-то отобразить что в условии функции смены статуса, что был отправлен запрос
Типо запрос когда отправляется, меняется  возможность смены статуса 
а как надо?)

2023-04-11 19:06 UTC, ievetrov requested changes

2023-04-11 19:06 UTC, ievetrov commented on src/main/kotlin/lesson_16/lesson_16_task_4.kt
> +    private var orderStatusChanging = false
"поменять можно только оставив заявку менеджеру" – имеется в виду, что напрямую нельзя, а для этого будем использовать специальный метод. это весь функционал) ну если такая опция добавлена, то надо как-то придумать, чтоб возвращать флаг в исходное положение

2023-04-12 12:45 UTC, ievetrov requested changes

2023-04-12 12:45 UTC, ievetrov commented on src/main/kotlin/lesson_16/lesson_16_task_4.kt
> +    private var orderStatusChanging = false
Все, я понял тебя )) Сложно сформулировано условие.

> Поменять статус заказа можно только отправив заявку менеджеру.

Имелось в виду, что отправка заявки менеджеру ( sendRequest() ) приводит к изменению статуса changeStatus(...). Метод sendRequest() - публичный, changeStatus - приватный.

А ты видимо понял, что после фактической отправки заявки, становится возможным сменить статус )

2023-04-13 07:18 UTC, ievetrov approved these changes

2023-04-13 14:43 UTC, merged